apiVersion: v1
kind: Service
metadata:
  name: flask-hello-svc
spec:
  type: ClusterIP
  selector:
    app: flask-hello
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
